### ISSUE TITLE
tabmode save-layout restore-layout don't work unless workspace is a number

### ISSUE THREAD

**Issue by michaelmrose** [BiagioFesta/i3-autolayout#12]
On a multimonitor system with workspaces that consist of either one letter or one number system seems to behave oddly on workspaces that are not numbers. It seems to want to effect the monitor with the cursor. This could be the result of two assumptions that the monitor that has the mouse is the active one and treating workspace names as numbers as numbers instead of strings. With mouse warping none the cursor stays when we change ws so cursor and focused workspace is distinct from this.

 Also workspaces are more reasonably strings that can contain numeric characters.

i3-autolayout 0.2.3 i3 version 4.22 void linux 

I'm happy to test any updates to this whenever convenient.

Thanks,
Michael

**Comment by BiagioFesta** [comment]
Thank you for reporting this!

Can you please provide more information to reproduce this? For instance, a minimal/small configuration-steps explaining the expected and instead the current behavior?

I've tried a multi-monitor configuration where:
```

                             ┌─────────────┐
    ┌──────────────────────┐ │             │
    │                      │ │             │
    │                      │ │   monitor 2 │
    │    monitor 1         │ │             │
    │                      │ │ workspace h │
    │    workspace 1       │ │             │
    │                      │ │             │
    │                      │ │             │
    └──────────────────────┘ │             │
                             │             │
                             │             │
                             │             │
                             └─────────────┘

```

(I've used `i3-msg 'rename workspace 2 to "h"'`)

But it seems I am missing something because I cannot reproduce (even trying having different cursor positions)

Thank you
